[starboard]
title = "V LIVE ─ 이달의 소녀(LOONA) ─ Star Board"
url = "https://vlive.tv/channel/E1F3A7/board/4386?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
contentSelector = "em[class^='writer']"
waitUntil = "networkidle"

[notice]
title = "V LIVE ─ 이달의 소녀(LOONA) ─ Notice"
url = "https://vlive.tv/channel/E1F3A7/board/950?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "em[class^='writer']"
waitUntil = "networkidle"

[search_loona]
title = "V LIVE ─ 검색 ─ 이달의 소녀"
url = "https://m.vlive.tv/search/videos?query=%EC%9D%B4%EB%8B%AC%EC%9D%98+%EC%86%8C%EB%85%80&sort=PUBDATE?lang=ko"
entrySelector = "ul.video_list li.video_list_cont"
titleSelector = "a.video_tit"
linkSelector = "a.video_tit"
contentSelector = "div.video_date a.name"
imageSelector = "a.thumb_area img"
waitUntil = "networkidle"